### PR TITLE
Changed linux script to open it with gedit

### PR DESCRIPTION
**Pull request by ankush-0x90**

### CODE REVIEW

**Comment by sujitdhond142** [comment]
Please remove main.txt file from commit (file is uncessary) and resend pull request.

**Comment by ankush-0x90** [comment]
@sujitdhond142 
Okey will do it but why That So?

**Comment by ankush-0x90** [comment]
Now Lets merge it @sujitdhond142  :)

**Comment by ankush-0x90** [comment]
aceept it!! Its fine now

**Pull request merged**
